name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Android SDK and Licenses
        uses: android-actions/setup-android@v3

      - name: Install Buildozer and Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev openjdk-17-jdk

      - name: Compile APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-agronomica-apk
          path: bin/*.apk
      - name: Compile APK with Buildozer
        run: |
          buildozer -v android debug
