name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git python3-pip python3-setuptools \
          libtool autoconf libssl-dev libffi-dev liblzma-dev openjdk-17-jdk zip unzip zlib1g-dev \
          ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixin-dev libsdl2-ttf-dev libportmidi-dev \
          libswscale-dev libavformat-dev libavcodec-dev pkg-config
        pip install --upgrade pip
        pip install "cython<3.0.0" buildozer

    - name: Build with Buildozer
      run: |
        export MAKEFLAGS="-j2"
        buildozer -v android debug
      env:
        ACCEPT_BUILD_NDK_LICENSES: "1"

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: package-apk
        path: bin/*.apk
