name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Usando a Action oficial para evitar conflitos de variáveis de ambiente de SDK/NDK nativas da máquina
      - name: Buildozer Action
        uses: Artemusa/buildozer-action@v1
        with:
          command: buildozer -v android debug
          repository_root: .
